### ISSUE TITLE
Image CSS

### ISSUE THREAD

**Issue by Wakkos** [wycks/WP-Skeleton-Theme#9]
Hello, 

Since it's a standar, why not add 

``` css
img {
max-width: 100%;
height: auto;
}
```

So big images won't overload its container?

I can make a pull request if you want.
